### Fake blog 1
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Kokkikoulu",
  "author": "Seppo Kakkunen",
  "url": "http://kokkikoulu.com",
  "likes": 1000
}

### Fake blog 2
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Juoksukoulu",
  "author": "Jaakko Jalkanen",
  "url": "http://jaakonlenkkipolku.com",
  "likes": 1
}